### ISSUE TITLE
!Ref is an unknown tag

### ISSUE THREAD

**Issue by devhops** [mwpearce/vscode-cfn-nag#1]
Hi!

If I use the short syntax for `Ref` in my template, it is flagged as an unknown tag, despite it being valid syntax.

```
  KeyNameID:
    Description: 'The SSH Keyname ID'
    Value: !Ref KeyName
```

![image](https://user-images.githubusercontent.com/539676/58990006-e9686a80-87dc-11e9-87dc-35ab255325dd.png)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html

This also occurs if I use `!GetAttr` which is the short syntax for `Fn::GetAttr`. The long versions work fine.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html

**Comment by mwpearce** [comment]
That's likely coming from the yaml linter build into VSCode.  I get around that problem by adding the following to my VSCode settings (either settings.json in your workspace or user settings.json) :

```
{
   "yaml.customTags": [
        "!Join sequence",
        "!Ref",
        "!Equals sequence",
        "!And sequence",
        "!Or sequence",
        "!Not sequence",
        "!Base64",
        "!Cidr sequence",
        "!If sequence",
        "!FindInMap sequence",
        "!GetAtt",
        "!GetAZs",
        "!ImportValue",
        "!Select sequence",
        "!Split sequence",
        "!Sub sequence",
        "!Sub",
        "!Transform",
        "!Condition"
    ]
}
```
