### ISSUE TITLE
SyntaxError in Output

### ISSUE THREAD

**Issue by benmontour-wf** [mwpearce/vscode-cfn-nag#2]
Getting this error recently using this extension. Let me know if I can provide more details. This error repeats five time and then stops trying.

vscode-cfn-nag v0.3.1
cfn_nag v0.4.14

```
SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (/Users/User/.vscode/extensions/eastman.vscode-cfn-nag-0.3.1/server/out/server.js:197:38)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
[Info  - 9:42:56 AM] Connection to server got closed. Server will restart.
Is CFN: true
Running.....cfn_nag --allow-suppression
Child process exited with code 2 and signal null
undefined:1
```

**Comment by mwpearce** [comment]
Install the latest version (0.3.2) and give it another shot.  I've added some error handling/logging.  I'd be curious what the logs show - the specific situation is one that I hadn't expected.

**Comment by benmontour-wf** [comment]
Latest version puts this into the Output section.

```
Is CFN: true
Running.....cfn_nag --allow-suppression
Child process exited with code 2 and signal null
Warn  - 10:07:17 AM] Unexpected response from cfn-nag: ------------------------------------------------------------
-
 ------------------------------------------------------------------------------------------------------------------------
```

I do see below the above message some of the cfn_nag rules that are triggered by a given template, but they don't show in the Problems section like they should.

**Comment by mwpearce** [comment]
Give it another try with version 0.3.3.  Looks like there's a change in the newer releases of cfn_nag that I wasn't taking into account.

**Comment by benmontour-wf** [comment]
No luck yet, still nothing showing in Problem tab. Output tab no longer shows detected cfn_nag issues, but does show the following error messages depending on cfn template selected.
```
Is CFN: true
Running...../Users/User/.rbenv/shims/cfn_nag --output-format=json,--allow-suppression
Child process exited with code 2 and signal null
Is CFN: true
Running...../Users/User/.rbenv/shims/cfn_nag --output-format=json,--allow-suppression
Child process exited with code 4 and signal null
Is CFN: true
Running...../Users/User/.rbenv/shims/cfn_nag --output-format=json,--allow-suppression
Child process exited with code 0 and signal null
```

**Comment by mwpearce** [comment]
Let's try one more time with 0.3.4.  There were more changes in the latest release of cfn_nag than I was aware of.
If you find that things still don't work, there's a new setting available "cfnNagLint.debug" that will output additional information.

**Comment by benmontour-wf** [comment]
Woohoo! That did the trick. Seems to be working again an no more errors thrown in Output.

**Comment by mwpearce** [comment]
Awesome!
