### ISSUE TITLE
Unexpected response from cfn_nag ([]), seems like file path is not given if cfnNagLint.path is set

### ISSUE THREAD

**Issue by kangastus** [mwpearce/vscode-cfn-nag#3]
When using `cfnNagLint.path` option it seems that the file path is not given as a parameter and cfn_nag returns and an empty array. This causes a `Unexpected response from cfn_nag` error in vscode output pane.

Full output:
```
Is CFN: true
Running.....sh cfn-nag.sh --version
[Info  - 11:43:01 AM] Current cfn_nag version: 0.4.33
[Info  - 11:43:01 AM] Version comparison = 1
[Info  - 11:43:01 AM] Running.....sh cfn-nag.sh --output-format=json,--allow-suppression
[Info  - 11:43:03 AM] [

]

[Warn  - 11:43:03 AM] Unexpected response from cfn_nag: [

]
```

In that shell script I have a line `echo "$@">debug.txt` which produces a file with following contents: `--output-format=json --allow-suppression`.

Ultimately my goal is to use that shell script to run the cfn_nag inside a docker container to avoid installing ruby locally. I'm not sure this is a good idea but this seemed like not intended behaviour. Enrinronment is MacOS 10.14.5

**Comment by kangastus** [comment]
**Update**: made the script available in the path, removed the `cfnNagLint.path` but the results are the same. So it's seems that maybe it's not related to the path setting.

**Comment by mwpearce** [comment]
Ultimately whatever is specified as cfnNagLint.path (defaults to just cfn_nag), should write its output to stdout.  That output should be the JSON returned by cfn_nag.  In your first example, your script is just writing its parameters to debug.txt and not sending anything to stdout so you should expect to get the error that's returned.

**Comment by kangastus** [comment]
Thank you for quick response! It does call `cfn_nag` and that returns an empty JSON array probably due to missing file path. The same can be seen by calling `cfn_nag --output-format=json --allow-suppression` directly without a file name. 

Here's the full script, sorry for omitting it earlier:
```
#!/usr/bin/env bash
echo "$@">debug.txt
docker run -v /${PWD}:/${PWD} stelligent/cfn_nag "$@"
```
I also tried defining `cfnNagLint.path` to `docker run -v /${PWD}:/${PWD} stelligent/cfn_nag` with the same result.

If I run `sh deployment-scripts/cfn_nag.sh --output-format=json --allow-suppression <path-to-file>` from terminal I get correct results. 

It would be nice if the debug output would print out the full command if it does include the file name.

The shell script approach worked nicely with cfn-lint for some reason.

**Comment by mwpearce** [comment]
The current approach is to pass the document contents to cfn-nag via stdin rather than specifying a file path.  That allows you to see errors without actually saving the current document in VSCode.
Debug output is actually displaying the full command.

**Comment by kangastus** [comment]
That makes sense. Thank you for your help.

I resolved my issue by specifying `"cfnNagLint.path": "docker run -i stelligent/cfn_nag",` and thus achieved my goal of not needing to install ruby. My earlier attempt was missing the Docker interactive flag.
