### ISSUE TITLE
[Request] Support for global blacklist and conditions files

### ISSUE THREAD

**Issue by bryanburke** [mwpearce/vscode-cfn-nag#4]
I would like to request support for cfn_nag's [Global Blacklist](https://github.com/stelligent/cfn_nag#global-blacklist) (`--blacklist-path`) and [Conditions Files](https://github.com/stelligent/cfn_nag#controlling-the-behavior-of-conditions) (`--condition-values-path`). These seem to be the only two cfn_nag features missing from this extension.

**Comment by mwpearce** [comment]
Thanks for the request.  I've just published a new version (v0.3.5) with support of those options.
